var hierarchy =
[
    [ "Application", null, [
      [ "AplikacjaDostepowa.App", "class_aplikacja_dostepowa_1_1_app.html", null ]
    ] ],
    [ "System.Windows.Application", null, [
      [ "AplikacjaDostepowa.App", "class_aplikacja_dostepowa_1_1_app.html", null ],
      [ "AplikacjaDostepowa.App", "class_aplikacja_dostepowa_1_1_app.html", null ]
    ] ],
    [ "System.Windows.Markup.IComponentConnector", null, [
      [ "AplikacjaDostepowa.MainWindow", "class_aplikacja_dostepowa_1_1_main_window.html", null ],
      [ "AplikacjaDostepowa.MainWindow", "class_aplikacja_dostepowa_1_1_main_window.html", null ],
      [ "AplikacjaDostepowa.Views.Admin.Nauczyciele", "class_aplikacja_dostepowa_1_1_views_1_1_admin_1_1_nauczyciele.html", null ],
      [ "AplikacjaDostepowa.Views.Admin.Nauczyciele", "class_aplikacja_dostepowa_1_1_views_1_1_admin_1_1_nauczyciele.html", null ],
      [ "AplikacjaDostepowa.Views.Administrator", "class_aplikacja_dostepowa_1_1_views_1_1_administrator.html", null ],
      [ "AplikacjaDostepowa.Views.Administrator", "class_aplikacja_dostepowa_1_1_views_1_1_administrator.html", null ],
      [ "AplikacjaDostepowa.Views.Archiwum", "class_aplikacja_dostepowa_1_1_views_1_1_archiwum.html", null ],
      [ "AplikacjaDostepowa.Views.Archiwum", "class_aplikacja_dostepowa_1_1_views_1_1_archiwum.html", null ],
      [ "AplikacjaDostepowa.Views.DodajNieobecność", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_nieobecno_xC5_x9B_xC4_x87.html", null ],
      [ "AplikacjaDostepowa.Views.DodajNieobecność", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_nieobecno_xC5_x9B_xC4_x87.html", null ],
      [ "AplikacjaDostepowa.Views.DodajUwagę", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_uwag_xC4_x99.html", null ],
      [ "AplikacjaDostepowa.Views.DodajUwagę", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_uwag_xC4_x99.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOceny", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOceny", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOgłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOgłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.Lekcja", "class_aplikacja_dostepowa_1_1_views_1_1_lekcja.html", null ],
      [ "AplikacjaDostepowa.Views.Lekcja", "class_aplikacja_dostepowa_1_1_views_1_1_lekcja.html", null ],
      [ "AplikacjaDostepowa.Views.Logowanie", "class_aplikacja_dostepowa_1_1_views_1_1_logowanie.html", null ],
      [ "AplikacjaDostepowa.Views.Logowanie", "class_aplikacja_dostepowa_1_1_views_1_1_logowanie.html", null ],
      [ "AplikacjaDostepowa.Views.Nieobecności", "class_aplikacja_dostepowa_1_1_views_1_1_nieobecno_xC5_x9Bci.html", null ],
      [ "AplikacjaDostepowa.Views.Nieobecności", "class_aplikacja_dostepowa_1_1_views_1_1_nieobecno_xC5_x9Bci.html", null ],
      [ "AplikacjaDostepowa.Views.Oceny", "class_aplikacja_dostepowa_1_1_views_1_1_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.Oceny", "class_aplikacja_dostepowa_1_1_views_1_1_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.Ogłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.Ogłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.Plan_lekcji", "class_aplikacja_dostepowa_1_1_views_1_1_plan__lekcji.html", null ],
      [ "AplikacjaDostepowa.Views.Plan_lekcji", "class_aplikacja_dostepowa_1_1_views_1_1_plan__lekcji.html", null ],
      [ "AplikacjaDostepowa.Views.Terminarz", "class_aplikacja_dostepowa_1_1_views_1_1_terminarz.html", null ],
      [ "AplikacjaDostepowa.Views.Terminarz", "class_aplikacja_dostepowa_1_1_views_1_1_terminarz.html", null ],
      [ "AplikacjaDostepowa.Views.UczenNaLekcjiKontrolka", "class_aplikacja_dostepowa_1_1_views_1_1_uczen_na_lekcji_kontrolka.html", null ],
      [ "AplikacjaDostepowa.Views.UczenNaLekcjiKontrolka", "class_aplikacja_dostepowa_1_1_views_1_1_uczen_na_lekcji_kontrolka.html", null ],
      [ "AplikacjaDostepowa.Views.Uwagi", "class_aplikacja_dostepowa_1_1_views_1_1_uwagi.html", null ],
      [ "AplikacjaDostepowa.Views.Uwagi", "class_aplikacja_dostepowa_1_1_views_1_1_uwagi.html", null ]
    ] ],
    [ "System.Windows.Markup.InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "AplikacjaDostepowa.Models.LekcjaModel", "class_aplikacja_dostepowa_1_1_models_1_1_lekcja_model.html", null ],
    [ "AplikacjaDostepowa.Models.Nauczyciel", "class_aplikacja_dostepowa_1_1_models_1_1_nauczyciel.html", null ],
    [ "AplikacjaDostepowa.Models.UczenNaLekcji", "class_aplikacja_dostepowa_1_1_models_1_1_uczen_na_lekcji.html", null ],
    [ "AplikacjaDostepowa.Models.User", "class_aplikacja_dostepowa_1_1_models_1_1_user.html", null ],
    [ "System.Windows.Controls.UserControl", null, [
      [ "AplikacjaDostepowa.Views.Admin.Nauczyciele", "class_aplikacja_dostepowa_1_1_views_1_1_admin_1_1_nauczyciele.html", null ],
      [ "AplikacjaDostepowa.Views.Admin.Nauczyciele", "class_aplikacja_dostepowa_1_1_views_1_1_admin_1_1_nauczyciele.html", null ],
      [ "AplikacjaDostepowa.Views.Admin.Nauczyciele", "class_aplikacja_dostepowa_1_1_views_1_1_admin_1_1_nauczyciele.html", null ],
      [ "AplikacjaDostepowa.Views.Administrator", "class_aplikacja_dostepowa_1_1_views_1_1_administrator.html", null ],
      [ "AplikacjaDostepowa.Views.Administrator", "class_aplikacja_dostepowa_1_1_views_1_1_administrator.html", null ],
      [ "AplikacjaDostepowa.Views.Administrator", "class_aplikacja_dostepowa_1_1_views_1_1_administrator.html", null ],
      [ "AplikacjaDostepowa.Views.Archiwum", "class_aplikacja_dostepowa_1_1_views_1_1_archiwum.html", null ],
      [ "AplikacjaDostepowa.Views.Archiwum", "class_aplikacja_dostepowa_1_1_views_1_1_archiwum.html", null ],
      [ "AplikacjaDostepowa.Views.Archiwum", "class_aplikacja_dostepowa_1_1_views_1_1_archiwum.html", null ],
      [ "AplikacjaDostepowa.Views.DodajNieobecność", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_nieobecno_xC5_x9B_xC4_x87.html", null ],
      [ "AplikacjaDostepowa.Views.DodajNieobecność", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_nieobecno_xC5_x9B_xC4_x87.html", null ],
      [ "AplikacjaDostepowa.Views.DodajNieobecność", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_nieobecno_xC5_x9B_xC4_x87.html", null ],
      [ "AplikacjaDostepowa.Views.DodajUwagę", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_uwag_xC4_x99.html", null ],
      [ "AplikacjaDostepowa.Views.DodajUwagę", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_uwag_xC4_x99.html", null ],
      [ "AplikacjaDostepowa.Views.DodajUwagę", "class_aplikacja_dostepowa_1_1_views_1_1_dodaj_uwag_xC4_x99.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOceny", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOceny", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOceny", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOgłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOgłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.DodawanieOgłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_dodawanie_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.Lekcja", "class_aplikacja_dostepowa_1_1_views_1_1_lekcja.html", null ],
      [ "AplikacjaDostepowa.Views.Lekcja", "class_aplikacja_dostepowa_1_1_views_1_1_lekcja.html", null ],
      [ "AplikacjaDostepowa.Views.Lekcja", "class_aplikacja_dostepowa_1_1_views_1_1_lekcja.html", null ],
      [ "AplikacjaDostepowa.Views.Logowanie", "class_aplikacja_dostepowa_1_1_views_1_1_logowanie.html", null ],
      [ "AplikacjaDostepowa.Views.Logowanie", "class_aplikacja_dostepowa_1_1_views_1_1_logowanie.html", null ],
      [ "AplikacjaDostepowa.Views.Logowanie", "class_aplikacja_dostepowa_1_1_views_1_1_logowanie.html", null ],
      [ "AplikacjaDostepowa.Views.Nieobecności", "class_aplikacja_dostepowa_1_1_views_1_1_nieobecno_xC5_x9Bci.html", null ],
      [ "AplikacjaDostepowa.Views.Nieobecności", "class_aplikacja_dostepowa_1_1_views_1_1_nieobecno_xC5_x9Bci.html", null ],
      [ "AplikacjaDostepowa.Views.Nieobecności", "class_aplikacja_dostepowa_1_1_views_1_1_nieobecno_xC5_x9Bci.html", null ],
      [ "AplikacjaDostepowa.Views.Oceny", "class_aplikacja_dostepowa_1_1_views_1_1_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.Oceny", "class_aplikacja_dostepowa_1_1_views_1_1_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.Oceny", "class_aplikacja_dostepowa_1_1_views_1_1_oceny.html", null ],
      [ "AplikacjaDostepowa.Views.Ogłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.Ogłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.Ogłoszenia", "class_aplikacja_dostepowa_1_1_views_1_1_og_xC5_x82oszenia.html", null ],
      [ "AplikacjaDostepowa.Views.Plan_lekcji", "class_aplikacja_dostepowa_1_1_views_1_1_plan__lekcji.html", null ],
      [ "AplikacjaDostepowa.Views.Plan_lekcji", "class_aplikacja_dostepowa_1_1_views_1_1_plan__lekcji.html", null ],
      [ "AplikacjaDostepowa.Views.Plan_lekcji", "class_aplikacja_dostepowa_1_1_views_1_1_plan__lekcji.html", null ],
      [ "AplikacjaDostepowa.Views.Terminarz", "class_aplikacja_dostepowa_1_1_views_1_1_terminarz.html", null ],
      [ "AplikacjaDostepowa.Views.Terminarz", "class_aplikacja_dostepowa_1_1_views_1_1_terminarz.html", null ],
      [ "AplikacjaDostepowa.Views.Terminarz", "class_aplikacja_dostepowa_1_1_views_1_1_terminarz.html", null ],
      [ "AplikacjaDostepowa.Views.UczenNaLekcjiKontrolka", "class_aplikacja_dostepowa_1_1_views_1_1_uczen_na_lekcji_kontrolka.html", null ],
      [ "AplikacjaDostepowa.Views.UczenNaLekcjiKontrolka", "class_aplikacja_dostepowa_1_1_views_1_1_uczen_na_lekcji_kontrolka.html", null ],
      [ "AplikacjaDostepowa.Views.UczenNaLekcjiKontrolka", "class_aplikacja_dostepowa_1_1_views_1_1_uczen_na_lekcji_kontrolka.html", null ],
      [ "AplikacjaDostepowa.Views.Uwagi", "class_aplikacja_dostepowa_1_1_views_1_1_uwagi.html", null ],
      [ "AplikacjaDostepowa.Views.Uwagi", "class_aplikacja_dostepowa_1_1_views_1_1_uwagi.html", null ],
      [ "AplikacjaDostepowa.Views.Uwagi", "class_aplikacja_dostepowa_1_1_views_1_1_uwagi.html", null ]
    ] ],
    [ "System.Windows.Window", null, [
      [ "AplikacjaDostepowa.MainWindow", "class_aplikacja_dostepowa_1_1_main_window.html", null ],
      [ "AplikacjaDostepowa.MainWindow", "class_aplikacja_dostepowa_1_1_main_window.html", null ]
    ] ],
    [ "Window", null, [
      [ "AplikacjaDostepowa.MainWindow", "class_aplikacja_dostepowa_1_1_main_window.html", null ]
    ] ]
];